export const allCourses = [
    {
        id: 1,
        title: "Introduction to Python Programming",
        course_content: "A beginner's guide to Python syntax and basic data structures.",
        category: "Science and Technology",
        owner: "arsen",
        created_at: "2025-10-20T10:00:00Z",
    },
    {
        id: 2,
        title: "Advanced CSS Layouts with Flexbox and Grid",
        course_content: "Master modern web design techniques.",
        category: "Web Development",
        owner: "emily",
        created_at: "2025-11-01T14:30:00Z",
    },
    {
        id: 3,
        title: "Financial Accounting Basics",
        course_content: "Understanding balance sheets and income statements.",
        category: "Business and Finance",
        owner: "jess",
        created_at: "2025-09-15T09:15:00Z",
    },
    {
        id: 4,
        title: "Public Speaking and Presentation Skills",
        course_content: "Techniques for overcoming stage fright and delivering impactful speeches.",
        category: "Personal Development",
        owner: "steph",
        created_at: "2025-10-25T11:45:00Z",
    },
    {
        id: 5,
        title: "Data Visualization with R and ggplot2",
        course_content: "Creating beautiful and informative statistical graphics.",
        category: "Data Science",
        owner: "qin",
        created_at: "2025-11-10T16:00:00Z",
    },
    {
        id: 6,
        title: "Digital Painting Fundamentals in Procreate",
        course_content: "Learn brush control, layers, and color theory for digital art.",
        category: "Arts and Design",
        owner: "maria",
        created_at: "2025-08-01T12:00:00Z",
    },
    {
        id: 7,
        title: "Modern JavaScript Frameworks: React Hook Flow",
        course_content: "In-depth guide to state management and side effects in React.",
        category: "Web Development",
        owner: "kate",
        created_at: "2025-11-20T17:30:00Z",
    },
    {
        id: 8,
        title: "Introduction to Machine Learning Models",
        course_content: "Exploring supervised and unsupervised learning algorithms.",
        category: "Science and Technology",
        owner: "ken",
        created_at: "2025-10-05T08:00:00Z",
    },
    {
        id: 9,
        title: "The Basics of Project Management (Scrum/Agile)",
        course_content: "Understanding agile methodologies and sprint planning.",
        category: "Business and Finance",
        owner: "sarah",
        created_at: "2025-09-01T13:45:00Z",
    },
];

